[server]
host = "0.0.0.0"
#port = "5600"
#storage = "peewee"
cors_origins = "*"

[server.custom_static]

[server-testing]
#host = "localhost"
#port = "5666"
#storage = "peewee"
#cors_origins = ""

[server-testing.custom_static]
